version: '3.8'

services:
  flight-service:
    build: .
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - flight-net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flight-net

volumes:
  redis_data:

networks:
  flight-net:
